#!/usr/bin/env python
'''
Copyright (C) 2010, Digium, Inc.
Terry Wilson <twilson@digium.com>

This program is free software, distributed under the terms of
the GNU General Public License Version 2.
'''

import sys
sys.path.append("lib/python")
from asterisk.cdr import AsteriskCSVCDRLine
from asterisk.CDRTestCase import CDRTestCase
from twisted.internet import reactor

class SIP_Dial_Busy_Test(CDRTestCase):
    def __init__(self):
        CDRTestCase.__init__(self)
        self.add_expectation('cdrtest_local', AsteriskCSVCDRLine(
            destination="1",
            dcontext="default",
            channel="Local/1@default-.*",
            disposition="BUSY",
            amaflags="DOCUMENTATION"))

def main():
    test = SIP_Dial_Busy_Test()
    test.start_asterisk()
    reactor.run()
    test.stop_asterisk()
    return test.results()

if __name__ == '__main__':
    sys.exit(main())

# vim:sw=4:ts=4:expandtab:textwidth=79
