#!/usr/bin/env bash
#
# Copyright (C) 2014, Fairview 5 Engineering, LLC
# George Joseph <george.joseph@fairview5.com>
#
# This program is free software, distributed under the terms of
# the GNU General Public License Version 2.
#

print_help() {
	echo "$1: Pretty print the output of runtests.py"
	echo "runtests.py ... | $1 [ --show-errors ] [ --verbose ] [ --term_width=n ]"
	echo "                     [ --no-color ] [ --no-timer ]"
	echo "     --show-errors:  If a test fails, show the output."
	echo "     --verbose:      Regardless of test status, show the output."
	echo "     --term-width=n: Force output to span 'n' columns."
	echo "     --no-color:     Don't use escape sequences to display color."
	echo "     --no-timer:     Don't display the timer as tests run."
	echo "                     Together, --no-color and --no-timer make the output"
	echo "                     suitable for redirecting to a file."
}

if [ -t 0 ] ; then
	print_help $(basename $0)
	exit 1
fi

SHOW_ERRORS=0
VERBOSE=0
NO_COLOR=0
NO_TIMER=0
TERM_WIDTH=0
declare -ix test_timeout=0

for a in "$@" ; do
	OPTION_COUNT+=1
	case "$a" in
		--*=*)
			[[ $a =~ --([^=]+)=(.*) ]]
			l=${BASH_REMATCH[1]//-/_}
			r=${BASH_REMATCH[2]}
			eval ${l^^}=$r
			;;
		--*)
			[[ $a =~ --(.+) ]]
			l=${BASH_REMATCH[1]//-/_}
			eval ${l^^}=1
			;;
		*)
			print_help $(basename $0)
			exit 1
			;;
	esac
done

if [ x"$TERM" = x ] ; then
	NO_TIMER=1
	NO_COLOR=1
	if [ $TERM_WIDTH -le 0 ] ; then
		TERM_WIDTH=80
	fi
else
	TERM_WIDTH=$(tput cols)
fi


if [ $NO_COLOR -gt 0 ] ; then
	YELLOW=''
	GREEN=''
	RED=''
	BOLD=''
	NORM=''
else
	YELLOW='\033[01;33m'
	GREEN='\033[01;32m'
	RED='\033[01;31m'
	BOLD='\033[1m'
	NORM='\033[m'
fi

status_string="[nnnn of nnnn][Status][Pass][Fail] "

counter() {
	status=Running
	startsec=$SECONDS
	while(true) ; do
		sleep 0.25
		et=$(( $SECONDS - $startsec))
		time_left=$(( $test_timeout - et ))
		if [ $test_timeout -gt 0 -a $et -gt $(( ($test_timeout / 4) * 3 )) ] ; then
			if [ $time_left -ge 0 ] ; then
				printf "${YELLOW}[%12s %3ss ]${NORM}" "Hung in" $time_left
			fi
		else
			printf "[%12s %3ss ]" "Running for" $et
		fi
		tput cub 20
	done
}

echo -e "Calculating..."
declare -i run=0
declare -i runs=0
declare -ix runnable=0
declare -ix total=0
declare -ix passed=0
declare -ix failed=0
declare -ix timedout=0
declare -ix tests=0
declare -ix maxelapsed=0
declare -a failures
declare -a timeouts
declare testname=""
starttime=$SECONDS

unset buffer
declare -a buffer

trap 'kill $countpid &>/dev/null' INT ERR
while read line ; do
	[ -z "$line" ] && continue
	buffer+=("$line")

	### Running tests for Asterisk GIT-master-99dea9b (run 1 of 1)...
	### The version may or may not not be present.
	if [[ $line =~ ^Running\ tests\ for\ Asterisk[^\(]*\(run\ +([0-9]+)\ +of\ +([0-9]+)\)\.\.\. ]] ; then
		run=${BASH_REMATCH[1]}
		runs=${BASH_REMATCH[2]}
	fi
	### Tests to run: 11 * 1 time(s) = 11  Maximum test inactivity time: 120 sec.
	if [[ $run -eq 1 && $line =~ ^Tests\ to\ run:\ +([0-9]+)\ +\*\ +([0-9]+)\ +time\(s\)\ +=\ +([0-9]+)\ +Maximum.test.inactivity.time:.([-0-9-]+) ]] ; then
		runnable=$(( ${BASH_REMATCH[1]} * $runs ))
		export test_timeout=${BASH_REMATCH[4]}
		printf "=%.0s" $(seq 1 ${TERM_WIDTH}) ; echo
		echo "${line/-1/unlimited}"
		col=$(( ${TERM_WIDTH} - ${#status_string} ))
		printf "%-*.*s[%-12s][%s][${GREEN}%4s${NORM}][${RED}%4s${NORM}]\n" $col $col "Test" "  Test" "Status" "Pass" "Fail"
	fi

	if [[ $line =~ ^--\>.Running.test.\'(.+)\'.\.\.\. ]] ; then
		unset buffer
		declare -a buffer
		(( tests++ ))
		col=$(( ${TERM_WIDTH} - ${#status_string} -1 ))
		testname=${BASH_REMATCH[1]#*/}
		tnl=$(( ${#testname} - $col ))
		[ $tnl -le 0 ] && tnl=0
		testname=${testname:$tnl}
		printf "${BOLD}%-*.*s${NORM} [%4d of %4d]" $col $col ${testname} $tests $runnable
		st=$SECONDS
		countpid=-1
		if [ $NO_TIMER -eq 0 ] ; then
			counter &
			disown $!
			countpid=$!
		fi
	fi

	if [[ $line =~ ^Test\ *(\[\'[^\']+\',\ \')?tests/([^\' ]+)(\', \'[^\']+\'\])?\ *(passed|failed|timed\ out)$ ]] ; then
		test=${BASH_REMATCH[2]}
		_unused_arg=${BASH_REMATCH[3]}
		status=${BASH_REMATCH[4]}
		col=$(( ${TERM_WIDTH} - ${#status_string} ))
		et=$(( $SECONDS - $st ))
		[ $countpid -gt 0 ] && kill $countpid
		show=0

		if [[ $status = passed ]] ; then
			(( passed++ ))
			COLOR=${GREEN}
			label=Passed
			[[ $et -gt $maxelapsed ]] && maxelapsed=$et
			[ $VERBOSE -gt 0 ] && show=1
		fi
		if [[ $status = failed ]] ; then
			(( failed++ ))
			COLOR=${RED}
			label=Failed
			failures+=("FAILED: $test")
			[[ $et -gt $maxelapsed ]] && maxelapsed=$et
			[ $SHOW_ERRORS -gt 0 -o $VERBOSE -gt 0 ] && show=1
		fi
		if [[ $status = "timed out" ]] ; then
			(( failed++ ))
			(( timedout++ ))
			COLOR=${RED}
			label=Hung!!
			timeouts+=("TIMEDOUT: $test")
			[ $SHOW_ERRORS -gt 0 -o $VERBOSE -gt 0 ] && show=1
		fi
		printf "[${COLOR}%s${NORM}][${GREEN}%4d${NORM}][${RED}%4d${NORM}]\n" $label $passed $failed
		if [ $show -gt 0 ] ; then
			echo ---------------------------------------------------------------------
			printf "%s\n" "${buffer[@]}"
			echo ---------------------------------------------------------------------
		fi
		unset buffer
		declare -a buffer
	fi

done

for fail in "${failures[@]}" ; do
	echo -e "${RED}$fail${NORM}"
done
for to in "${timeouts[@]}" ; do
	echo -e "${YELLOW}$to${NORM}"
done

elapsed=$(( $SECONDS - $starttime ))
time="$(( $elapsed / 60 ))m $(( $elapsed % 60 ))s"
printf "+%.0s" $(seq 1 ${TERM_WIDTH}) ; echo
echo -e "Tests: $runnable   ${GREEN}Passed: $passed   ${RED}Failed: $failed   TimedOut: $timedout${NORM}   Time: $time\tLongest test: ${maxelapsed}s"
printf "=%.0s" $(seq 1 ${TERM_WIDTH}) ; echo

trap - INT ERR

[ $countpid -gt 0 ] && kill $countpid &>/dev/null
