#!/usr/bin/env python

'''
Copyright (C) 2019, Sangoma Technologies Corporation
Ben Ford <bford@digium.com>

This program is free software, distributed under the terms of
the GNU General Public License Version 2.
'''

import sys
import logging

from asterisk.test_case import TestCase
from asterisk.voicemail import VoiceMailMailboxManagement
from twisted.internet import reactor

LOGGER = logging.getLogger(__name__)

class PollingTest(TestCase):
    def __init__(self):
        TestCase.__init__(self)
        self.test_phase = 1
        self.create_asterisk()

    def stop_test(self, passed=False):
        self.set_passed(passed)
        self.stop_reactor()

    def handle_message_waiting(self, ami, event):

        if event.get("mailbox") != "1234@default":
            return

        old = int(event.get("old"))
        new = int(event.get("new"))
        waiting = int(event.get("waiting"))

        # Phase 1: We are looking for an INBOX count of 1
        if self.test_phase == 1:
            if new != 1 or waiting != 1:
                return
            if old != 0:
                self.stop_test()
            self.test_phase = 2
            if not self.voicemailManager.remove_mailbox("default", "1234"):
                LOGGER.error("Failed to remove voicemail")
                self.stop_test()
        # Phase 2: We don't expect there to be any messages
        elif self.test_phase == 2:
            if new != 0 or old != 0 or waiting != 0:
                LOGGER.error("Expected empty mailbox")
                self.stop_test()
            self.stop_test(True)

    def ami_connect(self, ami):
        ami.registerEvent("MessageWaiting", self.handle_message_waiting)

        self.voicemailManager = VoiceMailMailboxManagement(self.ast[0])
        self.voicemailManager.create_mailbox("default", "1234", True)

        formats = ["ulaw"]
        if not self.voicemailManager.create_dummy_voicemail("default", "1234", VoiceMailMailboxManagement.inbox_folder_name, 1, formats):
            LOGGER.error("Failed to create voicemail")
            self.stop_test()

    def run(self):
        TestCase.run(self)
        self.create_ami_factory()

def main():
    test = PollingTest()
    reactor.run()
    if not test.passed:
        return 1
    return 0

if __name__ == "__main__":
    sys.exit(main() or 0)
