/*
 * buildopts.h
 * Automatically generated
 */

#define AST_DEVMODE 1
#define DONT_OPTIMIZE 1
#define OPTIONAL_API 1
#define DO_CRASH 1
#define TEST_FRAMEWORK 1
#define AST_BUILDOPT_SUM "c1ede5e75208a56856a96370ccdead31"
#define AST_BUILDOPTS "OPTIONAL_API, DO_CRASH, TEST_FRAMEWORK"
#define AST_BUILDOPTS_ALL "DONT_OPTIMIZE, OPTIONAL_API, DO_CRASH, TEST_FRAMEWORK"
