#!/usr/bin/env python
'''
Copyright (C) 2010, Digium, Inc.
Terry Wilson <twilson@digium.com>

This program is free software, distributed under the terms of
the GNU General Public License Version 2.
'''

import sys
from time import sleep
import os
sys.path.append("lib/python")
from asterisk.asterisk import Asterisk
from asterisk.cdr import AsteriskCSVCDR, AsteriskCSVCDRLine
from asterisk.ami import AMI
from twisted.internet import reactor
from asterisk.CDRTestCase import CDRTestCase
import logging

class SIP_Dial_Transfer_Test(CDRTestCase):
    def __init__(self):
        CDRTestCase.__init__(self)
        self.add_expectation('cdrtest_local', AsteriskCSVCDRLine(
            destination="1",
            dcontext="default",
            channel="Local/1@default-.*",
            disposition="ANSWERED",
            amaflags="DOCUMENTATION"))
        self.add_expectation('cdrtest_local3', AsteriskCSVCDRLine(
            destination="3",
            dcontext="default",
            channel="Local/3@default-.*",
            disposition="ANSWERED",
            amaflags="DOCUMENTATION"))

def main():
    test = SIP_Dial_Transfer_Test()
    test.start_asterisk()
    reactor.run()
    test.stop_asterisk()
    return test.results()

if __name__ == '__main__':
    sys.exit(main())
