#!/usr/bin/env python
'''
Copyright (C) 2010, Digium, Inc.
Erin Spiceland <espiceland@digium.com>

This program is free software, distributed under the terms of
the GNU General Public License Version 2.
'''

import sys
from twisted.internet import reactor

sys.path.append("lib/python")
from asterisk.asterisk import Asterisk
from asterisk.TestCase import TestCase


class FastAGIControlStreamFileTest(TestCase):
    def __init__(self):
        TestCase.__init__(self)

        self.create_asterisk()
        self.create_fastagi_factory()

    def on_failure(self, reason):
        print 'Could not run CONTROL STREAM FILE: ', reason.getTraceback()
        self.agi.finish()

    # result of 0 indicates success
    def finish_test(self, result):
        if result is "0":
            self.passed = True

        self.result_changed()

    def fastagi_connect(self, agi):
        self.agi = agi
        print "Connection established."
        return agi.controlStreamFile("beep", "").addCallback(
            self.finish_test)

    def launch_test(self):
        print "Originating call to begin test."
        self.ast[0].cli_originate("Local/504@agitest extension echo@agitest")

    # Read result before timeout
    def result_changed(self):
        if self.passed is True:
            self.stop_reactor()

    def run(self):
        TestCase.run(self)
        self.launch_test()


def main():
    test = FastAGIControlStreamFileTest()
    test.start_asterisk()
    reactor.run()
    test.stop_asterisk()
    if test.passed is not True:
        return 1

    return 0

if __name__ == "__main__":
    sys.exit(main() or 0)
