#!/usr/bin/env python
'''
Copyright (C) 2010, Digium, Inc.
Erin Spiceland <espiceland@digium.com>

This program is free software, distributed under the terms of
the GNU General Public License Version 2.
'''

import sys
import os
from optparse import OptionParser
from twisted.internet import reactor
from starpy import fastagi

sys.path.append("lib/python")
from asterisk.asterisk import Asterisk
from asterisk.version import AsteriskVersion

workingdir = "/tmp/asterisk-testsuite/fastagi/channel-status"
testdir = "tests/fastagi"

class FastAGIChannelStatusTest:
    def __init__(self, argv):
        self.passed = {'4': False, '6':False}
        self.timeout = 30
        self.test = 4

        parser = OptionParser()
        parser.add_option("-v", "--version", dest="ast_version",
                          help="Asterisk version string")
        (options, args) = parser.parse_args(argv)
        self.ast_version = AsteriskVersion(options.ast_version)

        # Listen for results from dialplan
        self.agi_factory = fastagi.FastAGIFactory(self.do_test)
        reactor.listenTCP(4573, self.agi_factory, self.timeout, '127.0.0.1')
        reactor.callWhenRunning(self.run)

        self.ast1 = Asterisk(base=workingdir)
        self.ast1.install_configs("%s/configs/ast1" % (testdir))

    def on_answer_failure(self, reason):
        print 'Could not answer the call:', reason.getTraceback()

    def on_failure(self, reason):
        print 'Could not run deferred:', reason.getTraceback()

    def on_answer(self, status):
        self.do_test(self.agi)

    def get_deferred(self, agi):
        return agi.channelStatus(agi.variables['agi_channel'])

    def finish_test(self, status):
        print "status is", status
        self.passed[status] = (self.test == status)
        if self.test == 4:
            print "Answering call"
            self.test = 6
            self.agi.answer().addCallback(self.on_answer).addErrback(
                self.on_answer_failure)
        elif self.test == 6:
            self.result_changed()

    # This gets invoked by the dialplan when the call is answered
    # Disconnect agi and set test result values
    def do_test(self, agi):
        self.agi = agi
        if self.test == 4:
            print "Connection established. Testing for channel status code 4."
        elif self.test == 6:
            print "Testing for channel status code 6."

        return self.get_deferred(agi).addCallback(
            self.finish_test).addErrback(self.on_failure)

	# Read test results and dialplan globals
    def read_result(self):
        self.agi.finish()
        self.stop_reactor()
        if self.passed[4] is True and self.passed[6] is True:
            print "Success"
        else:
            print "Failed"

    def stop_reactor(self):
        print "Stopping Reactor ..."
        if reactor.running:
            reactor.stop()

    def launch_test(self):
        print "Originating call to begin test."
        self.ast1.cli_originate("Local/no_answer@agitest extension echo@agitest", blocking=False)

    def start_asterisk(self):
        print "Starting Asterisk"
        self.ast1.start()

    def stop_asterisk(self):
        print "Stopping Asterisk"
        self.ast1.stop()

    # Read result before timeout 
    def result_changed(self):
        if self.passed[6] is not None:
            self.read_result()

    def run(self):
        self.launch_test()
        reactor.callLater(self.timeout, self.stop_reactor)

def main(argv=None):
    if argv is None:
        argv = sys.argv

    test = FastAGIChannelStatusTest(argv)
    test.start_asterisk()
    reactor.run()
    test.stop_asterisk()
    if test.passed[4] is not True or test.passed[6] is not True:
        return 1

    return 0

if __name__ == "__main__":
    sys.exit(main() or 0)
