#!/usr/bin/env python
# vim: sw=3 et:
'''
Copyright (C) 2017, Voxbone, SA
Torrey Searle <torrey@voxbone.com>

This program is free software, distributed under the terms of
the GNU General Public License Version 2.
'''

import sys
import os
import re
import shutil
import logging
import signal
import subprocess
import time

from twisted.internet import reactor

sys.path.append("lib/python")
sys.path.append("utils")
from tempfile import NamedTemporaryFile
from asterisk.asterisk import Asterisk
from asterisk.sipp import SIPpTest

logger = logging.getLogger(__name__)
WORKING_DIR = os.path.abspath(os.path.dirname(__file__))
TEST_DIR = os.path.dirname(os.path.realpath(__file__))

e164 = "3200000000"


def main():
    sippA_statfile = NamedTemporaryFile(delete=True)

    SIPP_SCENARIOS = [
        {
            'scenario': 'B_PARTY.xml',
            '-i': '127.0.0.1',
            '-p': '5700',
        },
        {
            'scenario': 'A_PARTY.xml',
            '-i': '127.0.0.1',
            '-p': '5061',
            '-m': '1',
            '-s': e164,
            '-trace_stat': '-trace_stat',
            '-stf': sippA_statfile.name,
        }
    ]

    test = SIPpTest(WORKING_DIR, TEST_DIR, SIPP_SCENARIOS, test_config={'memcheck-delay-stop':7})
    test.reactor_timeout = 100

    reactor.run()

    if not test.passed:
        return 1

    ret_A = subprocess.call([WORKING_DIR + "/check_reinvite_rtt.py", sippA_statfile.name])
    if (ret_A != 0):
        logger.debug("Slow ReInvite Detected!")
        return 1

    return 0

if __name__ == "__main__":
    sys.exit(main() or 0)
