#!/usr/bin/env python
'''
Copyright (C) 2011, Digium, Inc.
Kinsey Moore <kmoore@digium.com>

This program is free software, distributed under the terms of
the GNU General Public License Version 2.
'''

import sys
import os

sys.path.append("lib/python")
from asterisk.sipp import SIPpTest


WORKING_DIR = "sip/codec_negotiation"
TEST_DIR = os.path.dirname(os.path.realpath(__file__))

SIPP_SCENARIOS = [
    {'scenario' : 'single_audio.xml',},
    {'scenario' : 'decline_incompat_audio.xml',},
    {'scenario' : 'single_video.xml',},
    {'scenario' : 'single_video_inverse.xml',},
    {'scenario' : 'decline_incompat_video.xml',},
    {'scenario' : 'single_text.xml',},
    {'scenario' : 'single_text_inverse.xml',},
    {'scenario' : 'decline_incompat_text.xml',},
    {'scenario' : 'single_image.xml',},
    {'scenario' : 'single_image_inverse.xml',},
    {'scenario' : 'avt_streams.xml',},
    {'scenario' : 'multistream.xml',},
    {'scenario' : 'fax_sim.xml',},
    {'scenario' : 'decline_crypto.xml',},
    {'scenario' : 'orderstream.xml',},
]

# set port numberings and timeouts
port = 5061
def update_entry(entry):
    global port
    entry['-p'] = "%d" % port
    port += 1

# generate SIPP scenarios with appropriate port numbers and the config to go with it
def main():
    [update_entry(i) for i in SIPP_SCENARIOS]
    test = SIPpTest(WORKING_DIR, TEST_DIR, SIPP_SCENARIOS)
    return test.run()


if __name__ == "__main__":
    sys.exit(main())


# vim:sw=4:ts=4:expandtab:textwidth=79
