#!/usr/bin/env python
'''
Copyright (C) 2012, Digium, Inc.
Walter Doekes <walter+asterisk@wjd.nu>

This program is free software, distributed under the terms of
the GNU General Public License Version 2.
'''
import os, sys

sys.path.append('lib/python')

from twisted.internet import reactor
from asterisk.sipp import SIPpTest

TEST_DIR = os.path.dirname(os.path.realpath(__file__))
SIPP_SCENARIOS = [{'scenario': 'call.xml'}]


def main():
    test = SIPpTest('UNUSED_PARAMETER', TEST_DIR, SIPP_SCENARIOS)
    reactor.run()
    if not test.passed:
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())

# vim:sw=4:ts=4:expandtab:textwidth=79
