#!/usr/bin/env python
'''
Copyright (C) 2012, Digium, Inc.
Kinsey Moore <kmoore@digium.com>

This program is free software, distributed under the terms of
the GNU General Public License Version 2.
'''

import sys
import logging

sys.path.append("lib/python")
from asterisk.SimpleTestCase import SimpleTestCase
from twisted.internet import reactor

LOGGER = logging.getLogger(__name__)

class ConnectedLineTest(SimpleTestCase):
    def verify_event(self, event):
        if event['userevent'] != 'CLStatus':
            return False

        if event['arg1'] != '45':
            return False

        if event['arg2'] != '4':
            return False

        LOGGER.info("Got connected line event")
        return True

def main():
    test = ConnectedLineTest()
    test.start_asterisk()
    reactor.run()
    test.stop_asterisk()

    if not test.passed:
        return 1

    return 0

if __name__ == "__main__":
    sys.exit(main() or 0)

