#!/usr/bin/env python
'''
Copyright (C) 2012, Digium, Inc.
Mark Michelson <mmichelson@digium.com>

This program is free software, distributed under the terms of
the GNU General Public License Version 2.
'''
import sys
import os
import logging

sys.path.append("lib/python")

from asterisk.asterisk import Asterisk
from asterisk.TestCase import TestCase
from asterisk.sipp import SIPpScenario
from twisted.internet import reactor

logger = logging.getLogger(__name__)
TEST_DIR = os.path.dirname(os.path.realpath(__file__))

SIPP_SUBSCRIBE =  {
    'scenario' : 'subscribe.xml',
    '-p' : '5061',
    '-s' : 'bob',
}

class NominalStateChange(TestCase):
    def __init__(self):
        TestCase.__init__(self)
        self.create_asterisk()
        self.sipTest = SIPpScenario(TEST_DIR, SIPP_SUBSCRIBE)
        self.sippPassed = False
        self.notifyPassed = True

    def testComplete(self, result):
        self.sippPassed = True
        self.stop_reactor()

    def originateComplete(self, ami, event):
        # We successfully set presence, now let's change device state
        # so the SIPp test can conclude
        if event.get("userevent") != "Presence":
            return

        ami.originate(channel = "Local/callbob@default", application
                = "Echo").addErrback(self.handleOriginateFailure)

    def runSippTest(self):
        self.sipTest.run(self).addCallback(self.testComplete)

        self.ami[0].originate(channel = "Local/away@default", application =
                "Echo").addErrback(self.handleOriginateFailure)

    def inspectPresence(self, ami, event):
        # For this test, we expect none of these events.
        # If we get any, we fail.
        if event.get("state") != "DIGIUM_PRESENCE_SENT":
            return

        logger.error("Unexpected Digium Presence NOTIFY received")
        self.notifyPassed = False

    def ami_connect(self, ami):
        self.ast[ami.id].cli_exec("sip set debug on")
        ami.registerEvent("TestEvent", self.inspectPresence)
        ami.registerEvent("UserEvent", self.originateComplete)
        self.runSippTest()

    def stop_asterisk(self):
        ''' Kill the SIPp test if it didn't exit '''
        if not self.sipTest.exited:
            self.sipTest.kill()

    def run(self):
        TestCase.run(self)
        self.create_ami_factory()

def main():
    test = NominalStateChange()
    reactor.run()
    if not test.sippPassed or not test.notifyPassed:
        return 1
    return 0

if __name__ == "__main__":
    sys.exit(main() or 0)
