#!/usr/bin/env python
# vim: sw=3 et:
'''
Copyright (C) 2011, Digium, Inc.
Matthew Nicholson <mnicholson@digium.com>

This program is free software, distributed under the terms of
the GNU General Public License Version 2.
'''

import sys
import os
import re
import shutil
import logging
import signal
import subprocess
import time

from twisted.internet import reactor

sys.path.append("lib/python")
sys.path.append("utils")
from asterisk.asterisk import Asterisk
from asterisk.sipp import SIPpTest

logger = logging.getLogger(__name__)
WORKING_DIR = os.path.abspath(os.path.dirname(__file__))
TEST_DIR = os.path.dirname(os.path.realpath(__file__))

e164 = "3200000000"
sippA_logfile = WORKING_DIR + "/A_PARTY.log"
sippA_errfile = WORKING_DIR + "/A_PARTY_ERR.log"
sippA_statfile = WORKING_DIR + "/A_PARTY_STAT.log"

sippB_logfile = WORKING_DIR + "/B_PARTY.log"
sippB_errfile = WORKING_DIR + "/B_PARTY_ERR.log"

SIPP_SCENARIOS = [
    {
        'scenario' : 'B_PARTY.xml',
        '-i' : '127.0.0.1',
        '-p' : '5700',
        '-message_file' : sippB_logfile,
        '-error_file' : sippB_errfile,
        '-trace_msg' : '-trace_err',
    },
    {
        'scenario' : 'A_PARTY.xml',
        '-i' : '127.0.0.1',
        '-p' : '5061',
        '-s' : e164,
        '-message_file' : sippA_logfile,
        '-error_file' : sippA_errfile,
        '-trace_msg' : '-trace_err',
        '-trace_stat' : '-trace_stat',
        '-stf' : sippA_statfile,
    }
]

def main():
    test = SIPpTest(WORKING_DIR, TEST_DIR, SIPP_SCENARIOS)
    logger.info ("Running against asterisk version %s" %test.ast_version)
		   
    test.reactor_timeout = 100;

    dump_A = WORKING_DIR + "/carrier_rtp.log"
    dump_B = WORKING_DIR + "/customer_rtp.log"
    rtpdump_A = subprocess.Popen(["rtpdump", "-t","5", "-F","ascii","-d","101","-o",dump_A, "127.0.0.1/9000"])
    rtpdump_B = subprocess.Popen(["rtpdump", "-t","5", "-F","ascii","-d","101","-o",dump_B, "127.0.0.1/8000"])

    reactor.run()

    # Kill the RTPDUMP, pass it the signal"
    rtpdump_A.send_signal(signal.SIGINT)	
    rtpdump_A.wait()
    rtpdump_B.send_signal(signal.SIGINT)	
    rtpdump_B.wait()

    #Verify that audio packets were routed in both directions after G711 fallback
    if (os.path.getsize(dump_B) == 0):
        logger.error("No RTP routed towards customer ...failing the test")
        return 1
    if (os.path.getsize(dump_A) == 0):
        logger.error("No RTP routed towards carrier ...failing the test")
        return 1

    return 0

if __name__ == "__main__":
    sys.exit(main() or 0)

