#!/usr/bin/env python
'''
Copyright (C) 2022, Sangoma, Inc.


This program is free software, distributed under the terms of
the GNU General Public License Version 2.
'''

import sys
import logging
from attended_transfer import Transfer

from twisted.internet import reactor

sys.path.append("lib/python")
from asterisk.test_case import TestCase

logger = logging.getLogger(__name__)

class LocalTest(TestCase):
    def __init__(self):
        TestCase.__init__(self)
        self.create_asterisk(1)
        self.event_count = 0
        self.success_count = 0

    def run(self):
        TestCase.run(self)
        self.create_ami_factory()

    def ami_connect(self, ami):
        transfer = Transfer(self)
        transfer.start_calls()


def main():
    test = LocalTest()
    reactor.run()

    if not test.passed:
        return 1

    return 0

if __name__ == "__main__":
    sys.exit(main() or 0)

