#!/usr/bin/env python
"""
Copyright (C) 2015, Digium, Inc.
Ashley Sanders <asanders@digium.com>

This program is free software, distributed under the terms of
the GNU General Public License Version 2.
"""


import logging
import requests
import sys
import re

sys.path.append("lib/python")

from twisted.internet import reactor
from asterisk.test_case import TestCase

LOGGER = logging.getLogger(__name__)

BASE_URL   = "http://127.0.0.1:8088/httpstatus%d"

EXPECTED_STATUS_CODES = [404, 403, 403]

class HttpClientTest(TestCase):
    """Responsible for making a request to the http-server and then parsing
    response headers to verify that the value returned for 'Server' matches
    the expected value."""

    def __init__(self):
        """Constructor."""

        TestCase.__init__(self)
        self.create_asterisk(1)

    def run(self):
        """Runs the test."""

        TestCase.run(self)

        for i in range(0, 3):
            status = EXPECTED_STATUS_CODES[i]

            url = BASE_URL % (i+1)

            self.run_scenario(url, status)
            if self.passed == False:
                break

        LOGGER.debug("Stopping reactor...")
        self.stop_reactor()

    def run_scenario(self, url, expected_status):
        """Runs an individual test scenario.

        Keyword Arguments:
        url             --  The url to use for making the server request
        expected_name   --  The name that the server is expected to return
                            in its response headers
        """

        LOGGER.debug("Running %s", self)

        resp = requests.get(url)
        LOGGER.debug("[resp]: [%r]", resp)

        status = resp.status_code
        LOGGER.debug("[status]: [%d]", status)

        if status != expected_status:
            LOGGER.debug("[%d] != [%d]", status, expected_status)
            self.set_passed(False)
            return

        self.set_passed(True)
        return

def main():
    """Main entry-point for the test."""

    test = HttpClientTest()
    reactor.run()

    if test.passed:
        return 0
    return 1

if __name__ == "__main__":
    sys.exit(main() or 0)
