#!/usr/bin/env python

import sys
import logging
import logging.config
import os
import shutil
from twisted.internet import reactor

sys.path.append("lib/python")

from asterisk.TestCase import TestCase

logger = logging.getLogger(__name__)

class SIPACLTest(TestCase):

    # Preps test objects and configuration additions as well as copies TLS keys to test folder.
    def __init__(self):
        TestCase.__init__(self)
        self.test_components = []

        #success evaluation stuff
        self.test_index = 0

        #test1 - No named ACL, calling available only to 127.0.0.1
        self.add_test_component("test1_1", "allow")
        self.add_test_component("test1_2", "deny")
        self.add_test_component("test1_3", "deny")
        self.add_test_component("test1_4", "deny")

        #test2 - Same permissible addresses as test 1, but while using a named ACL from the local configuration
        self.add_test_component("test2_1", "allow")
        self.add_test_component("test2_2", "deny")
        self.add_test_component("test2_3", "deny")
        self.add_test_component("test2_4", "deny")

        #test3 - Multiple named ACL rules from local configuration. Only 127.0.0.2 should be allowed to call.
        self.add_test_component("test3_1", "deny")
        self.add_test_component("test3_2", "allow")
        self.add_test_component("test3_3", "deny")
        self.add_test_component("test3_4", "deny")

        #test4 - An undefined rule is used. All addresses should be rejected from calling.
        self.add_test_component("test4_1", "deny")
        self.add_test_component("test4_2", "deny")
        self.add_test_component("test4_3", "deny")
        self.add_test_component("test4_4", "deny")

        #test5 - A set of 3 named ACLs stored in realtime is used. Collectively only 127.0.0.3 should be allowed to call.
        self.add_test_component("test5_1", "deny")
        self.add_test_component("test5_2", "deny")
        self.add_test_component("test5_3", "allow")
        self.add_test_component("test5_4", "deny")

        self.create_asterisk()

    def add_test_component(self, test, expectation):
        this_tuple = test, expectation
        self.test_components.append(this_tuple)

    # Once the AMI Factory connects to the AMI, this function fires.
    def ami_connect(self, ami):
        ami.registerEvent('Hangup', self.evaluate_hangup)
        self.test_start(ami)

    def test_start(self, ami):
        logger.info("Starting test %d - %s:" % (self.test_index, self.test_components[self.test_index][0]))

        # The following variable tracks events that occur as a result of the following originate. We expect two events in all cases.
        # In the case of a successful call, we expect two hangups. If the call is unsuccessful, we expect a hangup and an AMI command error.
        self.events_received = 0
        self.success_conditions = 0
        self.failure_conditions = 0

        # Storage for the events (failures and AMI hangups) that came in -- stored in case of something going wrong.
        self.events = []

        # There are callbacks that would lose the AMI, so we need to hold onto it within the test object.
        self.last_active_ami = ami

        ami.originate(channel = "SIP/%s/s" % self.test_components[self.test_index][0], application = "Echo").addErrback(self.evaluate_originate_error)

    def evaluate_hangup(self, ami, event):
        self.events_received += 1
        self.events.append(event)

        # evaluate if whether the hangup indicates success or failure
        reason = event.get('cause-txt')
        if reason == "Normal Clearing":
            self.success_conditions += 1
        elif reason == "Call Rejected":
            self.failure_conditions += 1

        # If we've got two events of any kind, the call is finished and we can move on to the evaluation
        if self.events_received == 2:
            self.evaluate_call()

    def evaluate_originate_error(self, reason):
        self.events.append(reason)
        self.events_received += 1
        self.failure_conditions += 1
        if self.events_received == 2:
            self.evaluate_call()

    def evaluate_call(self):
        if self.test_components[self.test_index][1] == "allow" and self.success_conditions == 2:
            logger.info("Test %d - %s: Call Succeeded as Expected." % (self.test_index, self.test_components[self.test_index][0]))
        elif self.test_components[self.test_index][1] == "deny" and self.failure_conditions == 2:
            logger.info("Test %d - %s: Call Failed as Expected." % (self.test_index, self.test_components[self.test_index][0]))
        else:
            logger.error("Test %d - %s: Events received don't follow expectations. Test Failed." % (self.test_index, self.test_components[self.test_index][0]))
            logger.error("Failure Triggering Events Received: %s" % self.events)
            self.passed = False
            self.stop_reactor()
            return

        # Go on to the next test.
        self.test_index += 1
        if self.test_index < len(self.test_components):
            self.test_start(self.last_active_ami)
        else:
            logger.info("All tests evaluated as expected. Test Successful.")
            self.passed = True
            self.stop_reactor()
            return

    # Sets up reactor and AMI connection
    def run(self):
        TestCase.run(self)
        self.create_ami_factory()


def main():
    TEST_DIR = os.path.dirname(os.path.realpath(__file__))
    DB_PATH = TEST_DIR + "/realtime.sqlite3"
    TMP_DB_PATH = "/tmp/realtime.sqlite3"
    shutil.copyfile(DB_PATH, TMP_DB_PATH)
    test = SIPACLTest()
    reactor.run()
    os.remove(TMP_DB_PATH)

    if test.passed:
        return 0
    return 1

if __name__ == "__main__":
    sys.exit(main() or 0)


# vim:sw=4:ts=4:expandtab:textwidth=79

