#!/usr/bin/env python
'''
Copyright (C) 2010, Digium, Inc.
Terry Wilson <twilson@digium.com>

This program is free software, distributed under the terms of
the GNU General Public License Version 2.
'''

import sys
from time import sleep
import os
sys.path.append("lib/python")
from asterisk.asterisk import Asterisk
from asterisk.cdr import AsteriskCSVCDR, AsteriskCSVCDRLine
from asterisk.ami import AMI
from twisted.internet import reactor
import logging

workingdir = "/tmp/asterisk-testsuite/console_fork_after_busy_forward"
testdir = "tests/cdr/console_fork_after_busy_forward"

class Test:
    def __init__(self):
        self.passed = False

        reactor.callLater(60, self.abort)

        asterisk1 = Asterisk(base=workingdir)
        asterisk1.install_configs("%s/configs1" % (testdir))

        asterisk2 = Asterisk(base=workingdir)
        asterisk2.install_configs("%s/configs2" % (testdir))

        asterisk1.start()
        asterisk2.start()

        self.asterisk1 = asterisk1
        self.asterisk2 = asterisk2

        self.ami = AMI(self.start, self.abort, timeout=20)
        self.ami.login()

    def start(self, ami):
        ami.registerEvent('Hangup', self.end)
        self.asterisk1.cli_exec("console dial 1@default")

    def stop_asterisk(self):
        self.asterisk1.stop()
        self.asterisk2.stop()

    def abort(self):
        print "Aborting ..."
        self.stop_asterisk()
        if reactor.running:
            for call in reactor.getDelayedCalls():
                call.cancel()
            reactor.stop()

    def end(self, ami, event):
        if event.get('channel').lower() != "console/dsp":
            return

        self.stop_asterisk()
        cdr1 = AsteriskCSVCDR(fn="%s/var/log/asterisk/cdr-csv/Master.csv" % (self.asterisk1.base))
        cdr2 = AsteriskCSVCDR(fn="%s/var/log/asterisk/cdr-csv/Master.csv" % (self.asterisk2.base))

        records = []

        records.append(AsteriskCSVCDRLine(disposition='ANSWERED', dchannel='SIP/test-.*',
            dcontext='default', amaflags='DOCUMENTATION', uniqueid=cdr1[0].uniqueid,
            accountcode='', callerid='', userfield='', source='', destination='1',
            lastapp='Dial', lastarg='SIP/2@test', channel='Console/dsp', billsec=cdr1[0].billsec))

        records.append(AsteriskCSVCDRLine(disposition='ANSWERED', dchannel='SIP/test-.*',
            dcontext='default', amaflags='DOCUMENTATION', uniqueid=cdr1[0].uniqueid,
            accountcode='', callerid='', userfield='', source='', destination='1',
            lastapp='Dial', lastarg='SIP/2@test', channel='Console/dsp', billsec=cdr1[0].billsec))

        cdr1_expect = AsteriskCSVCDR(records=records)

        cdr2_expect = AsteriskCSVCDR(records=[AsteriskCSVCDRLine(accountcode="",
            source="asterisk", destination="2", dcontext="default",
            callerid='"asterisk" <asterisk>', channel="SIP/.*5065-.*",
            dchannel="", lastapp="Hangup", lastarg="", disposition="ANSWERED",
            amaflags="DOCUMENTATION")])

        if len(cdr1) < 2:
            print "Fewer cdr records than expected! (%d)" % len(cdr1)
            reactor.stop()
            return

        if int(cdr1[0].duration) < int(cdr1[1].duration):
            print "Fail: Original CDR duration shorter than forked"
            sys.exit(-1)

        if cdr1_expect.match(cdr1) and cdr2_expect.match(cdr2):
            print "Success"
            self.passed = True
        else:
            print "Failure"

        reactor.stop()


def main():
    logging.basicConfig()
    test = Test()
    reactor.run()
    return not test.passed

if __name__ == '__main__':
    sys.exit(main())

# vim:sw=4:ts=4:expandtab:textwidth=79
