#!/usr/bin/env python
'''
Copyright (C) 2013, Digium, Inc.
David M. Lee, II <dlee@digium.com>

This program is free software, distributed under the terms of
the GNU General Public License Version 2.
'''

import logging
import requests
import sys

from requests import codes
from twisted.internet import reactor

sys.path.append("lib/python")
from asterisk.test_case import TestCase

LOGGER = logging.getLogger(__name__)

HOST='localhost'
PORT=8088

def build_url(*args):
    return "http://%s:%d/%s" %\
           (HOST, PORT, '/'.join([str(arg) for arg in args]))

class Scenario(object):
    def __init__(self, userpass, method, expected_response):
        self.userpass = userpass
        self.method = method
        self.expected_response = expected_response

    def __repr__(self):
        return '{ userpass=%s, method=%s, expected=%d }' % (
            self.userpass, self.method.__name__, self.expected_response)

    def eval(self, str, test, resp):
        if self.expected_response != resp.status_code:
            LOGGER.error("Expected %d, got %d (%s). %s - %s" % (
                self.expected_response, resp.status_code, resp.text, self, str))
            test.passed = False

    def run(self, test):
        LOGGER.debug("Running %s" % self)
        if self.userpass is None:
            # Test no authentication
            resp = self.method(build_url('ari', 'channels'))
            self.eval('Unauthenticated', test, resp)
            return

        # Test basic auth
        resp = self.method(build_url('ari', 'channels'),
                           auth=self.userpass)
        self.eval('Basic', test, resp)

        # Test api_key auth
        resp = self.method(build_url('ari', 'channels'),
                           params={'api_key': "%s:%s" % self.userpass})
        self.eval('api_key', test, resp)


SCENARIOS=[
    Scenario(('user1', 'password'), requests.get, codes.okay),
    Scenario(('user2', 'password'), requests.get, codes.forbidden),
    Scenario(('user3', 'password'), requests.get, codes.forbidden)
]

class ARIAuthenticationTest(TestCase):
    def __init__(self):
        TestCase.__init__(self)
        self.passed = True
        self.create_asterisk()

    def run(self):
        try:
            for scenario in SCENARIOS:
                scenario.run(self)
        except:
            logging.exception("Exception caught during test")
            self.passed = False
        finally:
            self.stop_reactor()

def main():
    test = ARIAuthenticationTest()
    reactor.run()
    if test.passed:
        return 0
    return 1

if __name__ == "__main__":
    sys.exit(main() or 0)
