name: PRCPCheck
run-name: "PR ${{ github.event.number }} CPCheck by ${{ github.actor }}"
on:
  pull_request_target:
    types: [ labeled ]

jobs:
  PRCPCheck:
    name: "run-cpcheck"
    if: ${{ github.event.label.name == vars.CHERRY_PICK_TEST_LABEL }}
    concurrency:
      group: cpcheck-${{ github.base_ref }}-${{ github.ref_name }}
      cancel-in-progress: true
    uses: asterisk/asterisk-ci-actions/.github/workflows/TestsuitePRCPCheck.yml@main
