name: PRMerge
run-name: "PR ${{ github.event.number }} Merge by ${{ github.actor }}"
on:
  pull_request_target:
    types: [ labeled ]

jobs:
  PRMerge:
    name: "run-merge"
    if: contains(fromJSON(vars.MERGE_APPROVED_LABELS), github.event.label.name)
    concurrency:
      group: merge-${{ github.base_ref }}-${{ github.ref_name }}
      cancel-in-progress: true
    uses: asterisk/asterisk-ci-actions/.github/workflows/TestsuitePRMerge.yml@main
